name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "cypress.env.json"
          json: ${{ secrets.SECRET }}
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on-timeout: 120
          browser: chrome